#!/bin/bash

echo "Removing MImport Cache..."
rm -rf //var/mobile/Media/mImportCache.plist
rm -rf //var/mobile/Media/mimport_running
rm -rf //var/mobile/Media/mimport_running_uploader

echo "Running uicache..."
su mobile -c uicache

echo "RESPRING YOUR DEVICE!!!"
echo "RESPRING YOUR DEVICE!!!"
echo "RESPRING YOUR DEVICE!!!"
declare -a cydia
cydia=($CYDIA)
if [[ ${CYDIA+@} ]]; then
eval "echo 'finish:restart' >&${cydia[0]}"
fi

exit 0